#include "gic.h"

static u32 gic_irqs;


int gic_init(){
	u32 i;

	gic_irqs = (REGW(GIC_BASE+GIC_DIST_CTR) & 0x1f) * 32;
	REGW(GIC_BASE+GIC_DIST_CTRL) = GICD_DISABLE;

	for (i = 32; i < gic_irqs; i += 16)
		REGW(GIC_BASE+GIC_DIST_CONFIG + i /4) = GICD_INT_ACTLOW_LVLTRIG;
	for (i = 32; i < gic_irqs; i += 4)
		REGW(GIC_BASE+GIC_DIST_PRI+i) = GICD_INT_DEF_PRI_X4;
	for (i = 32; i < gic_irqs; i += 32) {
		REGW(GIC_BASE+GIC_DIST_ACTIVE_CLEAR+i/8)=GICD_INT_EN_CLR_X32;
		REGW(GIC_BASE+GIC_DIST_ENABLE_CLEAR+i/8)=GICD_INT_EN_CLR_X32;
	}
	REGW(GIC_BASE+GIC_DIST_ACTIVE_CLEAR) = GICD_INT_EN_CLR_X32;
	REGW(GIC_BASE+GIC_DIST_ENABLE_CLEAR) = GICD_INT_EN_CLR_PPI;
	REGW(GIC_BASE+GIC_DIST_ENABLE_SET) = GICD_INT_EN_SET_SGI;

	for (i = 0; i < 32; i += 4)
		REGW(GIC_BASE+GIC_DIST_PRI +i *4 / 4) = GICD_INT_DEF_PRI_X4;
	REGW(GIC_BASE+GIC_CPU_PRIMASK) = GICC_INT_PRI_THRESHOLD;

	i = REGW(GIC_BASE+GIC_CPU_CTRL);
	i &= GICC_DIS_BYPASS_MASK;
	REGW(GIC_BASE+GIC_CPU_CTRL)=i | 0 | GICC_ENABLE;

	REGW(GIC_BASE+GIC_DIST_CTRL) = GICD_ENABLE;

	return 0;
}